### PR TITLE
Actually fail CI if generation fails

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Also disables fail fast so other generators run even if one generator fails.

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@rom1504 This is the real situation of the project. Some versions actually fail, but so far the CI never fails if some generators compile, but fail during generation.

**Comment by rom1504** [comment]
Great, let's fix it

**Comment by AlexProgrammerDE** [comment]
@rom1504 Fixed! 🌮 
Ready for merge.

**Comment by rom1504** [comment]
Awesome

**Pull request merged**
